# Generated by Django 5.1.7 on 2025-04-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='father_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='photo',
            field=models.FileField(default='Not Provided', upload_to='photo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='signature',
            field=models.FileField(default='Not Provided', upload_to='signature/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='course',
            field=models.CharField(choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('BSC', 'B.Sc.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
