# Generated by Django 5.1.7 on 2025-04-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_studentapplication_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
    ]
