# Generated by Django 5.1.7 on 2025-04-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_studentapplication_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Physics', 'B.Sc. Physics'), ('Chemistry', 'B.Sc. Chemistry'), ('Electronics', 'B.Sc. Electronics'), ('Math', 'B.Sc. Mathematics'), ('CS', 'Computer Science'), ('BioMed', 'Biomedical Science'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('BCom', 'B.Com')], max_length=100)),
                ('photo', models.ImageField(upload_to='faculty_photos/')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
