# Generated by Django 5.1.7 on 2025-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_facultymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
