# Generated by Django 5.2 on 2025-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_studentapplication_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='document',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
