# Generated by Django 5.2 on 2025-04-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_studentapplication_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='signature',
            field=models.ImageField(upload_to='signature/'),
        ),
    ]
